#!/bin/bash
DOTFILES="${HOME}/.local/dotfiles"
DEPENDENCIES=("zsh" "batcat" "exa" "rg" "nvim" "kitty" "tmux")

if [ "$PWD" != ${DOTFILES} ]; then
	echo "this script must be run from ${DOTFILES}."
	exit 1;
else
	echo "bootstrapping to ${DOTFILES}..."
fi
echo

echo "check dependencies..."
for dep in "${DEPENDENCIES[@]}"; do
	if ! command -v ${d} &> /dev/null; then
		missing=1 
		echo "${dep} not installed." 
	fi
done
if [ -n "${missing}" ]; then
	echo "please install missing dependencies."
	exit 1
fi

echo "install oh-my-zsh..."
if [ -e "${HOME}/.oh-my-zsh" ]; then
	echo "    oh-my-zsh already installed! not doing anything."
else
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

echo "install tmux-themepack..."
if [ -e "${HOME}/.tmux-themepack" ]; then
	echo "    tmux-themepack already installed! not doing anything."
else
	git clone https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack
fi

echo "adding rcfiles..."
for file in $(find "${DOTFILES}/rcfiles/" -type d); do
	BASENAME=${file#"${DOTFILES}/rcfiles/"}
	mkdir -p "${HOME}/${BASENAME}"
done
for file in $(find "${DOTFILES}/rcfiles/" -type f); do
	BASENAME=${file#"${DOTFILES}/rcfiles/"}
	if [ -e "${HOME}/${BASENAME}" ]; then
		echo "    ${BASENAME} already exists! not doing anything."
		echo "    to fix this, backup your file and run: "
		echo "    ln -sT ${file} ${HOME}/${BASENAME}"
	else
		echo "    Linking in ${BASENAME}..."
		ln -sT "${file}" "${HOME}/${BASENAME}"
	fi
done

echo "installing vim plugins..."
nvim +PluginInstall +qall

echo "all done! relog to see changes."
