#!/bin/bash

if [ "$PWD" != "${HOME}/.local/dotfiles" ]; then
	echo "This script must be run from ${HOME}/.local/dotfiles"
	exit 1;
else
	echo "Bootstrapping to ${HOME}/.local/dotfiles..."
fi
echo

DOTFILES="${HOME}/.local/dotfiles"

if [ -e "${HOME}/.local/bin" ]; then
	echo "${HOME}/.local/bin exists! Backing up..."
	mv "${HOME}/.local/bin" "${HOME}/.local/bin.bckp"
fi

echo "Adding rcfiles..."
for file in $(find "${DOTFILES}/rcfiles/" -type f); do
	BASENAME=$(basename ${file})
	if [ -e "${HOME}/${BASENAME}" ]; then
		echo "    ${BASENAME} already exists! Not doing anything."
		echo "    To fix this, backup your file and run: "
		echo "    ln -sT ${file} ${HOME}/${BASENAME}"
	else
		echo "    Linking in ${BASENAME}..."
		ln -sT "${file}" "${HOME}/${BASENAME}"
	fi
done

echo "Install Vundle..."
if [ -e "${HOME}/.vim/bundle/Vundle.vim" ]; then
	echo "    vundle already installed! Not doing anything."
else
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	vim +PluginInstall +qall
fi

echo "Install tmux-themepack..."
if [ -e "${HOME}/.tmux-themepack" ]; then
	echo "    tmux-themepack already installed! Not doing anything."
else
	git clone https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack
	vim +PluginInstall +qall
fi

echo "All done! Relog to see changes."
